name: covid_care
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.7
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  flutter_svg: ^0.22.0
  google_fonts: ^2.0.0
  google_sign_in: ^4.5.1
  provider: ^5.0.0
  share: ^2.0.1
  toast: ^0.1.5
  upgrader: ^3.2.1
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: BrandFont
      fonts:
        - asset: fonts/Cagliostro-Regular.ttf
